### ISSUE TITLE
Crash reproduction

### ISSUE THREAD

**Issue by JuGGerNaunT** [PodeCaradox/Gm1KonverterCrossPlatform#11] opened 2020-04-23 14:32 UTC
I was able to reproduce [this](https://github.com/PodeCaradox/Gm1KonverterCrossPlatform/issues/7) crash.
1. Select tile_land3.gm1 item
2. Select tile_land8.gm1 item
3. Once again select tile_land3.gm1 item
4. Once again select tile_land8.gm1 item
5. Keep switching between those items. It takes like 10-20 switches until it crash. 

It isn't managed .net exception, so there is no callstack. Only this error if I run program under debugger
```
An unhandled exception of type 'System.AccessViolationException' occurred in SkiaSharp
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
```

**Comment by PodeCaradox** [comment] 2020-04-23 16:13
With my fixes for the new release there is no error, cant reproduce it. 
Or did you mean select a image from the gm1?

**Comment by JuGGerNaunT** [comment] 2020-04-23 16:33
Items in the right list. You need to switch items fast enough to reproduce it
It crashes only for tile_land3.gm1 and tile_land8.gm1. Switching between other items work fine.
I checked old version and it also crashes only for those 2 items.

**Comment by PodeCaradox** [comment] 2020-04-23 19:28
ok in my new version it is not crashing and i clicked so fast on my arrow keys up and down. It buffered the input and showed after i ended clicking the arrows the up and down but no error.

Wait do you get the error only in debug Mode? Or did you test with release. Because i tested release.

**Comment by JuGGerNaunT** [comment] 2020-04-24 08:37
> Or did you test with release. Because i tested release.

it was present in both modes. though in debug mode it was much easier to reproduce it, just with couple of switches. i committed pr, looks like it fix this issue.

**Comment by PodeCaradox** [comment] 2020-04-24 18:45
ok thanks i merged it

**Closed as completed** 2020-04-24 18:45 UTC
